### ISSUE TITLE
Dependency resolution code to go-debian?

### ISSUE THREAD

**Issue by tianon** [paultag/nmr#1]
As we discussed, it would be way cool to extract the dependency resolution code from here into more generalized functions over in go-debian (or elsewhere).

**Comment by paultag** [comment]
Totally. I forked the nmr candidate stuff over to https://github.com/paultag/go-resolver - but it needs a bit of work to be slightly smarter, but that's the bulk of it!

**Comment by tianon** [comment]
:+1:
